### ISSUE TITLE
Possible error in compatibility

### ISSUE THREAD

**Issue by mofhu** [CMRose3355/TomahaqCompanionProgram#4]
Dear,

I tried a minimized peptide list (no prime run yet) on Orbitrap Eclipse with Tune 3.3. I got the following log with error:

```
[4:12:58 PM]	Importing Modifications
[4:12:58 PM]	Determining Quantification Channels
[4:12:58 PM]	Importing Target Peptides
[4:12:58 PM]	Consolidating Data for GUI Tables
[4:12:58 PM]	Building XML
[4:12:58 PM]	Creating New Method
[4:12:58 PM]	Error! The specified xml (OrbitrapFusion) is not compatible with the instrument model (Unknown, OrbitrapEclipse)
```

Could you please give some suggestions/comments on it? Is Tune 3.3 (and/or Eclipse) supported? 

Many thanks!
Frank

**Comment by CMRose3355** [comment]
Hello Frank, I just updated the program and associated files with the correct XML .dll's from Tune 3.3. Let me know if this works for you. 

Best - Chris

**Comment by mofhu** [comment]
Great to hear from you, Chris!

I tried the new version of program. This time I got a message box of error (please find figure below). I also attached the error message below.

I used a simple peptide list (only with sequence column and no modifications) for this test. No raw file is chosen.

Best,
Frank

![Capture](https://user-images.githubusercontent.com/11144135/66727309-e2c7bf00-ee70-11e9-8ffb-7431a4f075a2.PNG)


```

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: The specified xml (OrbitrapFusion) is not compatible with the instrument model (Unknown, OrbitrapEclipse)
   at XmlMethodChanger.lib.MethodChanger.ModifyMethod(String methodTemplate, String methodModXML, String outputMethod, String model, String version, Boolean enableValidation) in C:\Users\rosec6\Desktop\meth-modifications-master\xmlmethodchanger\XmlMethodChanger.lib\MethodChanger.cs:line 192
   at TomahaqCompanion.TomahaqCompanionForm.createMethod_Click_1(Object sender, EventArgs e) in C:\Users\lumos\Documents\GitHub\TomahaqCompanion\TomahaqCompanion\TomahaqCompanionForm.cs:line 259
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2661.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
TomahaqCompanion
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Methods/TomahaqCompanionProgram-master/TomahaqCompanion/TomahaqCompanion.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2110.0 built by: NET47REL1LAST
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2634.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2661.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ZedGraph
    Assembly Version: 5.1.7.430
    Win32 Version: 5.1.7.430
    CodeBase: file:///D:/Methods/TomahaqCompanionProgram-master/TomahaqCompanion/ZedGraph.DLL
----------------------------------------
CSMSL
    Assembly Version: 0.3.7224.24160
    Win32 Version: 0.3.7224.24160
    CodeBase: file:///D:/Methods/TomahaqCompanionProgram-master/TomahaqCompanion/CSMSL.DLL
----------------------------------------
MethodChanger
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Methods/TomahaqCompanionProgram-master/TomahaqCompanion/MethodChanger.DLL
----------------------------------------
CSMSL.Thermo
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Methods/TomahaqCompanionProgram-master/TomahaqCompanion/CSMSL.Thermo.DLL
----------------------------------------
LumenWorks.Framework.IO
    Assembly Version: 3.9.1.0
    Win32 Version: 3.9.1
    CodeBase: file:///D:/Methods/TomahaqCompanionProgram-master/TomahaqCompanion/LumenWorks.Framework.IO.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2623.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Thermo.TNG.MethodXMLFactory
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///D:/Methods/TomahaqCompanionProgram-master/TomahaqCompanion/Thermo.TNG.MethodXMLFactory.DLL
----------------------------------------
Thermo.TNG.MethodXMLInterface
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///D:/Methods/TomahaqCompanionProgram-master/TomahaqCompanion/Thermo.TNG.MethodXMLInterface.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by CMRose3355** [comment]
Ok, so I had thought the issue was with the library - but it is likely with the xml I am generating and using to edit the method. I will work towards a longterm fix - but in the meantime, I placed an "Orbitrap Eclipse" check box under the "Advanced" tab. This will make sure the xml that is generated and used to edit the method has the correct instrument type in the file. I updated the program again - let me know if it works. 

Chris

**Comment by mofhu** [comment]
I got exactly the same error message. However, I did notice the line 2 of xml file auto-generated from my peptide list has changed from "OrbitrapFusion" to "OrbitrapEclipse" when I check the new check box.

By the way, I also noticed that two folder path in error message is not present in my case. Is it possible that some other xml format may lead to this?

```
C:\Users\rosec6\Desktop\meth-modifications-master\xmlmethodchanger\XmlMethodChanger.lib\MethodChanger.cs:line 192
C:\Users\lumos\Documents\GitHub\TomahaqCompanion\TomahaqCompanion\TomahaqCompanionForm.cs:line 259
```

Best,
Frank

**Comment by CMRose3355** [comment]
I have updated TomahaqCompanion and it should now work with Orbitrap Eclipse. You will need to check the "Orbtirap Eclipse" check box. If this error persists let me know.

**Comment by mofhu** [comment]
Great to know and many thanks, Chris! We will try and feedback to you.
